### ISSUE TITLE
mvn install does not work

### ISSUE THREAD

**Issue by JAnderton** [rawls238/Scientist4J#17]
Running `mvn install` causes a build failure.

```
~/p/Scientist4J ❯❯❯ mvn clean install
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 2 modules...
---------------------------------------------------
constituent[0]: file:/usr/local/Cellar/maven/3.3.9/libexec/lib/aether-api-1.0.2.v20150114.jar
constituent[1]: file:/usr/local/Cellar/maven/3.3.9/libexec/lib/aether-connector-basic-1.0.2.v20150114.jar
constituent[2]: file:/usr/local/Cellar/maven/3.3.9/libexec/lib/aether-impl-1.0.2.v20150114.jar
constituent[3]: file:/usr/local/Cellar/maven/3.3.9/libexec/lib/aether-spi-1.0.2.v20150114.jar
constituent[4]: file:/usr/local/Cellar/maven/3.3.9/libexec/lib/aether-transport-wagon-1.0.2.v20150114.jar
constituent[5]: file:/usr/local/Cellar/maven/3.3.9/libexec/lib/aether-util-1.0.2.v20150114.jar
constituent[6]: file:/usr/local/Cellar/maven/3.3.9/libexec/lib/aopalliance-1.0.jar
constituent[7]: file:/usr/local/Cellar/maven/3.3.9/libexec/lib/cdi-api-1.0.jar
constituent[8]: file:/usr/local/Cellar/maven/3.3.9/libexec/lib/commons-cli-1.2.jar
constituent[9]: file:/usr/local/Cellar/maven/3.3.9/libexec/lib/commons-io-2.2.jar
constituent[10]: file:/usr/local/Cellar/maven/3.3.9/libexec/lib/commons-lang-2.6.jar
constituent[11]: file:/usr/local/Cellar/maven/3.3.9/libexec/lib/commons-lang3-3.4.jar
constituent[12]: file:/usr/local/Cellar/maven/3.3.9/libexec/lib/guava-18.0.jar
constituent[13]: file:/usr/local/Cellar/maven/3.3.9/libexec/lib/guice-4.0-no_aop.jar
constituent[14]: file:/usr/local/Cellar/maven/3.3.9/libexec/lib/javax.inject-1.jar
constituent[15]: file:/usr/local/Cellar/maven/3.3.9/libexec/lib/jsoup-1.7.2.jar
constituent[16]: file:/usr/local/Cellar/maven/3.3.9/libexec/lib/jsr250-api-1.0.jar
constituent[17]: file:/usr/local/Cellar/maven/3.3.9/libexec/lib/maven-aether-provider-3.3.9.jar
constituent[18]: file:/usr/local/Cellar/maven/3.3.9/libexec/lib/maven-artifact-3.3.9.jar
constituent[19]: file:/usr/local/Cellar/maven/3.3.9/libexec/lib/maven-builder-support-3.3.9.jar
constituent[20]: file:/usr/local/Cellar/maven/3.3.9/libexec/lib/maven-compat-3.3.9.jar
constituent[21]: file:/usr/local/Cellar/maven/3.3.9/libexec/lib/maven-core-3.3.9.jar
constituent[22]: file:/usr/local/Cellar/maven/3.3.9/libexec/lib/maven-embedder-3.3.9.jar
constituent[23]: file:/usr/local/Cellar/maven/3.3.9/libexec/lib/maven-model-3.3.9.jar
constituent[24]: file:/usr/local/Cellar/maven/3.3.9/libexec/lib/maven-model-builder-3.3.9.jar
constituent[25]: file:/usr/local/Cellar/maven/3.3.9/libexec/lib/maven-plugin-api-3.3.9.jar
constituent[26]: file:/usr/local/Cellar/maven/3.3.9/libexec/lib/maven-repository-metadata-3.3.9.jar
constituent[27]: file:/usr/local/Cellar/maven/3.3.9/libexec/lib/maven-settings-3.3.9.jar
constituent[28]: file:/usr/local/Cellar/maven/3.3.9/libexec/lib/maven-settings-builder-3.3.9.jar
constituent[29]: file:/usr/local/Cellar/maven/3.3.9/libexec/lib/org.eclipse.sisu.inject-0.3.2.jar
constituent[30]: file:/usr/local/Cellar/maven/3.3.9/libexec/lib/org.eclipse.sisu.plexus-0.3.2.jar
constituent[31]: file:/usr/local/Cellar/maven/3.3.9/libexec/lib/plexus-cipher-1.7.jar
constituent[32]: file:/usr/local/Cellar/maven/3.3.9/libexec/lib/plexus-component-annotations-1.6.jar
constituent[33]: file:/usr/local/Cellar/maven/3.3.9/libexec/lib/plexus-interpolation-1.21.jar
constituent[34]: file:/usr/local/Cellar/maven/3.3.9/libexec/lib/plexus-sec-dispatcher-1.3.jar
constituent[35]: file:/usr/local/Cellar/maven/3.3.9/libexec/lib/plexus-utils-3.0.22.jar
constituent[36]: file:/usr/local/Cellar/maven/3.3.9/libexec/lib/slf4j-api-1.7.5.jar
constituent[37]: file:/usr/local/Cellar/maven/3.3.9/libexec/lib/slf4j-simple-1.7.5.jar
constituent[38]: file:/usr/local/Cellar/maven/3.3.9/libexec/lib/wagon-file-2.10.jar
constituent[39]: file:/usr/local/Cellar/maven/3.3.9/libexec/lib/wagon-http-2.10-shaded.jar
constituent[40]: file:/usr/local/Cellar/maven/3.3.9/libexec/lib/wagon-http-shared-2.10.jar
constituent[41]: file:/usr/local/Cellar/maven/3.3.9/libexec/lib/wagon-provider-api-2.10.jar
constituent[42]: file:/usr/local/Cellar/maven/3.3.9/libexec/conf/logging/
---------------------------------------------------
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/base/Strings
	at org.sonatype.nexus.maven.staging.deploy.DeployLifecycleParticipant.getPluginByGAFromContainer(DeployLifecycleParticipant.java:239)
	at org.sonatype.nexus.maven.staging.deploy.DeployLifecycleParticipant.getNexusMavenPluginFromContainer(DeployLifecycleParticipant.java:183)
	at org.sonatype.nexus.maven.staging.deploy.DeployLifecycleParticipant.getBuildPluginsNexusMavenPlugin(DeployLifecycleParticipant.java:164)
	at org.sonatype.nexus.maven.staging.deploy.DeployLifecycleParticipant.afterProjectsRead(DeployLifecycleParticipant.java:96)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:266)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.ClassNotFoundException: com.google.common.base.Strings
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 18 more
```

Commenting out `nexus-staging-maven-plugin` causes the build to pass (but causes loss of functionality?). Is there setup that's required to be able to install this artifact locally?

**Comment by JAnderton** [comment]
Travis CI should probably running `mvn install` to ensure the project installs correctly.
